// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-M-Uuy-gVWIWCYvGyIYR29TpBI9VKz8Y',
    appId: '1:86700303682:web:6f587e8456b060d6a9d4db',
    messagingSenderId: '86700303682',
    projectId: 'buyrent-9503b',
    authDomain: 'buyrent-9503b.firebaseapp.com',
    storageBucket: 'buyrent-9503b.appspot.com',
    measurementId: 'G-C9W0YQFM6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1l_WaUw2kJ7HJemXObO4ZhqkGn54pArI',
    appId: '1:86700303682:android:75519e9d64948fe7a9d4db',
    messagingSenderId: '86700303682',
    projectId: 'buyrent-9503b',
    storageBucket: 'buyrent-9503b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP3s5UR3HwRtgALjPNFVGnLao_E0rNBHA',
    appId: '1:86700303682:ios:a0f05afdcd2008b8a9d4db',
    messagingSenderId: '86700303682',
    projectId: 'buyrent-9503b',
    storageBucket: 'buyrent-9503b.appspot.com',
    iosBundleId: 'com.example.buyrent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP3s5UR3HwRtgALjPNFVGnLao_E0rNBHA',
    appId: '1:86700303682:ios:8ebf64891c65af84a9d4db',
    messagingSenderId: '86700303682',
    projectId: 'buyrent-9503b',
    storageBucket: 'buyrent-9503b.appspot.com',
    iosBundleId: 'com.example.buyrent.RunnerTests',
  );
}
